--- 
--- Configuration for construction limits
--- 

Stronghold.Construction.Config = {
    TowerDistance = 1500,
    LightBricksFactor = 1.2,

    -- Limit of recruiter buildings
    RecruitBuildingAmounts = {
        [1] = -1,
        [2] = -1,
        [3] = -1,
        [4] = -1,
        [5] = -1,
        [6] = -1,
        [7] = -1,
        [8] = -1,
    },
    -- Limit of cannon factories
    SmeltingBuildingAmounts = {
        [1] = 1,
        [2] = 1,
        [3] = 1,
        [4] = 1,
        [5] = 2,
        [6] = 2,
        [7] = 3,
        [8] = 3,
    },

    PlacementDistanceCheck = {
        -- Towers
        [UpgradeCategories.DarkBallistaTower] = 1500,
        [UpgradeCategories.DarkCannonTower]   = 1500,
        [UpgradeCategories.DarkWatchTower]    = 1500,
        [UpgradeCategories.DarkTower]         = 1500,
        [UpgradeCategories.Tower]             = 1500,
        [UpgradeCategories.BallistaTower]     = 1500,
        [UpgradeCategories.CannonTower]       = 1500,
        [UpgradeCategories.WatchTower]        = 1500,
    },

    EnemyDistanceCheck = {
        -- Towers
        [UpgradeCategories.DarkBallistaTower] = 6000,
        [UpgradeCategories.DarkCannonTower]   = 6000,
        [UpgradeCategories.DarkWatchTower]    = 6000,
        [UpgradeCategories.DarkTower]         = 6000,
        [UpgradeCategories.Tower]             = 6000,
        [UpgradeCategories.BallistaTower]     = 6000,
        [UpgradeCategories.CannonTower]       = 6000,
        [UpgradeCategories.WatchTower]        = 6000,
        -- Traps
        [UpgradeCategories.BearCage]          = 2500,
        [UpgradeCategories.DogCage]           = 2500,
        [UpgradeCategories.PitchPit]          = 2500,
        [UpgradeCategories.Traphole]          = 2500,
        -- Walls
        [UpgradeCategories.DarkWall]          = 3000,
        [UpgradeCategories.Palisade]          = 3000,
        [UpgradeCategories.Wall]              = 3000,
    },

    -- Check types for construction technology
    TypesToCheckForConstruction = {
        [Technologies.B_Beautification01]       = {Entities.PB_Beautification01},
        [Technologies.B_Beautification02]       = {Entities.PB_Beautification02},
        [Technologies.B_Beautification03]       = {Entities.PB_Beautification03},
        [Technologies.B_Beautification04]       = {Entities.PB_Beautification04},
        [Technologies.B_Beautification05]       = {Entities.PB_Beautification05},
        [Technologies.B_Beautification06]       = {Entities.PB_Beautification06},
        [Technologies.B_Beautification07]       = {Entities.PB_Beautification07},
        [Technologies.B_Beautification08]       = {Entities.PB_Beautification08},
        [Technologies.B_Beautification09]       = {Entities.PB_Beautification09},
        [Technologies.B_Beautification10]       = {Entities.PB_Beautification10},
        [Technologies.B_Beautification11]       = {Entities.PB_Beautification11},
        [Technologies.B_Beautification12]       = {Entities.PB_Beautification12},

        [Technologies.B_Headquarter]            = {Entities.PB_Headquarters1, Entities.PB_Headquarters2, Entities.PB_Headquarters3,},
        [Technologies.B_Outpost]                = {Entities.PB_Outpost1, Entities.PB_Outpost2, Entities.PB_Outpost3,},
        [Technologies.B_Archery]                = {Entities.PB_Archery1, Entities.PB_Archery2,},
        [Technologies.B_Barracks]               = {Entities.PB_Barracks1, Entities.PB_Barracks2,},
        [Technologies.B_Foundry]                = {Entities.PB_Foundry1, Entities.PB_Foundry2,},
        [Technologies.B_Stables]                = {Entities.PB_Stable1, Entities.PB_Stable2,},
        [Technologies.B_Tower]                  = {Entities.PB_Tower1},
        [Technologies.B_BallistaTower]          = {Entities.PB_Tower2},
        [Technologies.B_CannonTower]            = {Entities.PB_Tower3},
        [Technologies.B_Mercenary]              = {Entities.PB_MercenaryCamp1},
        [Technologies.B_BearCage]               = {Entities.PB_BearCage1},
        [Technologies.B_DogCage]                = {Entities.PB_DogCage1},
        [Technologies.B_PitchPit]               = {Entities.PB_PitchPit1},
        [Technologies.B_Traphole]               = {Entities.PB_Traphole1},

        [Technologies.B_Alchemist]              = {Entities.PB_Alchemist1, Entities.PB_Alchemist2,},
        [Technologies.B_Bank]                   = {Entities.PB_Bank1, Entities.PB_Bank2,},
        [Technologies.B_Blacksmith]             = {Entities.PB_Blacksmith1, Entities.PB_Blacksmith2, Entities.PB_Blacksmith3,},
        [Technologies.B_Brickworks]             = {Entities.PB_Brickworks1, Entities.PB_Brickworks2,},
        [Technologies.B_ExecutionerPlace]       = {Entities.PB_ExecutionerPlace1,},
        [Technologies.B_Farm]                   = {Entities.PB_Farm1, Entities.PB_Farm2, Entities.PB_Farm3},
        [Technologies.B_GunsmithWorkshop]       = {Entities.PB_GunsmithWorkshop1, Entities.PB_GunsmithWorkshop2,},
        [Technologies.B_Monastery]              = {Entities.PB_Monastery1, Entities.PB_Monastery2, Entities.PB_Monastery3,},
        [Technologies.B_MasterBuilderWorkshop]  = {Entities.PB_MasterBuilderWorkshop,},
        [Technologies.B_Market]                 = {Entities.PB_Market1, Entities.PB_Market2,},
        [Technologies.B_PowerPlant]             = {Entities.PB_PowerPlant1,},
        [Technologies.B_Residence]              = {Entities.PB_Residence1, Entities.PB_Residence2, Entities.PB_Residence3,},
        [Technologies.B_Sawmill]                = {Entities.PB_Sawmill1, Entities.PB_Sawmill2,},
        [Technologies.B_StoneMason]             = {Entities.PB_StoneMason1, Entities.PB_StoneMason2,},
        [Technologies.B_Tavern]                 = {Entities.PB_Tavern1, Entities.PB_Tavern2,},
        [Technologies.B_University]             = {Entities.PB_University1, Entities.PB_University2,},
        [Technologies.B_Village]                = {Entities.PB_VillageCenter1, Entities.PB_VillageCenter2, Entities.PB_VillageCenter3,},
        [Technologies.B_Weathermachine]         = {Entities.PB_WeatherTower1,},

        -- Those are here so that it just work's...
        [Technologies.B_Palisade]               = {Entities.PB_PalisadeDistorted,},
        [Technologies.B_TowerDark]              = {Entities.PB_DarkTower1},
        [Technologies.B_BallistaTowerDark]      = {Entities.PB_DarkTower2},
        [Technologies.B_CannonTowerDark]        = {Entities.PB_DarkTower3},
        [Technologies.B_Wall]                   = {Entities.PB_WallDistorted,},
        [Technologies.B_WallDark]               = {Entities.PB_DarkWallDistorted,},
    },

    -- Check types for upgrade technologies
    TypesToCheckForUpgrade = {
        [Technologies.UP1_Alchemist]            = {Entities.PB_Alchemist1, Entities.PB_Alchemist2,},
        [Technologies.UP1_Archery]              = {Entities.PB_Archery1, Entities.PB_Archery2,},
        [Technologies.UP1_Bank]                 = {Entities.PB_Bank1, Entities.PB_Bank2},
        [Technologies.UP1_Barracks]             = {Entities.PB_Barracks1, Entities.PB_Barracks2,},
        [Technologies.UP1_Blacksmith]           = {Entities.PB_Blacksmith1, Entities.PB_Blacksmith2, Entities.PB_Blacksmith3,},
        [Technologies.UP1_Brickworks]           = {Entities.PB_Brickworks1, Entities.PB_Brickworks2,},
        [Technologies.UP1_Claymine]             = {Entities.PB_ClayMine1, Entities.PB_ClayMine2, Entities.PB_ClayMine3,},
        [Technologies.UP1_Farm]                 = {Entities.PB_Farm1, Entities.PB_Farm2, Entities.PB_Farm3,},
        [Technologies.UP1_Foundry]              = {Entities.PB_Foundry1, Entities.PB_Foundry2,},
        [Technologies.UP1_GunsmithWorkshop]     = {Entities.PB_GunsmithWorkshop1, Entities.PB_GunsmithWorkshop2,},
        [Technologies.UP1_Headquarter]          = {Entities.PB_Headquarters1, Entities.PB_Headquarters2, Entities.PB_Headquarters3,},
        [Technologies.UP1_Ironmine]             = {Entities.PB_IronMine1, Entities.PB_IronMine2, Entities.PB_IronMine3,},
        [Technologies.UP1_Market]               = {Entities.PB_Market1, Entities.PB_Market2,},
        [Technologies.UP1_Monastery]            = {Entities.PB_Monastery1, Entities.PB_Monastery2, Entities.PB_Monastery3,},
        [Technologies.UP1_Residence]            = {Entities.PB_Residence1, Entities.PB_Residence2, Entities.PB_Residence3,},
        [Technologies.UP1_Sawmill]              = {Entities.PB_Sawmill1, Entities.PB_Sawmill2,},
        [Technologies.UP1_Stables]              = {Entities.PB_Stable1, Entities.PB_Stable2,},
        [Technologies.UP1_StoneMason]           = {Entities.PB_StoneMason1, Entities.PB_StoneMason2,},
        [Technologies.UP1_Stonemine]            = {Entities.PB_StoneMine1, Entities.PB_StoneMine2, Entities.PB_StoneMine3,},
        [Technologies.UP1_Sulfurmine]           = {Entities.PB_SulfurMine1, Entities.PB_SulfurMine2, Entities.PB_SulfurMine3,},
        [Technologies.UP1_Tavern]               = {Entities.PB_Tavern1, Entities.PB_Tavern2,},
        [Technologies.UP1_Tower]                = {Entities.PB_Tower2, Entities.PB_Tower3},
        [Technologies.UP1_University]           = {Entities.PB_University1, Entities.PB_University2,},
        [Technologies.UP1_Village]              = {Entities.PB_VillageCenter1, Entities.PB_VillageCenter2, Entities.PB_VillageCenter3,},
        [Technologies.UP1_Outpost]              = {Entities.PB_Outpost1, Entities.PB_Outpost2, Entities.PB_Outpost3,},

        [Technologies.UP2_Blacksmith]           = {Entities.PB_Blacksmith1, Entities.PB_Blacksmith2, Entities.PB_Blacksmith3,},
        [Technologies.UP2_Claymine]             = {Entities.PB_ClayMine1, Entities.PB_ClayMine2, Entities.PB_ClayMine3,},
        [Technologies.UP2_Farm]                 = {Entities.PB_Farm1, Entities.PB_Farm2, Entities.PB_Farm3,},
        [Technologies.UP2_Headquarter]          = {Entities.PB_Headquarters1, Entities.PB_Headquarters2, Entities.PB_Headquarters3,},
        [Technologies.UP2_Ironmine]             = {Entities.PB_IronMine1, Entities.PB_IronMine2, Entities.PB_IronMine3,},
        [Technologies.UP2_Monastery]            = {Entities.PB_Monastery1, Entities.PB_Monastery2, Entities.PB_Monastery3,},
        [Technologies.UP2_Residence]            = {Entities.PB_Residence1, Entities.PB_Residence2, Entities.PB_Residence3,},
        [Technologies.UP2_Stonemine]            = {Entities.PB_StoneMine1, Entities.PB_StoneMine2, Entities.PB_StoneMine3,},
        [Technologies.UP2_Sulfurmine]           = {Entities.PB_SulfurMine1, Entities.PB_SulfurMine2, Entities.PB_SulfurMine3,},
        [Technologies.UP2_Tower]                = {Entities.PB_Tower2, Entities.PB_Tower3,},
        [Technologies.UP2_Village]              = {Entities.PB_VillageCenter1, Entities.PB_VillageCenter2, Entities.PB_VillageCenter3,},
        [Technologies.UP2_Outpost]              = {Entities.PB_Outpost1, Entities.PB_Outpost2, Entities.PB_Outpost3,},

        [Technologies.UP3_Tower]                = {Entities.PB_Tower1, Entities.PB_Tower4,},

        -- Those are here so that it just work's...
        [Technologies.UP1_TowerDark]            = {Entities.PB_DarkTower2, Entities.PB_DarkTower3},
        [Technologies.UP2_TowerDark]            = {Entities.PB_DarkTower2, Entities.PB_DarkTower3,},
        [Technologies.UP3_TowerDark]            = {Entities.PB_DarkTower1, Entities.PB_DarkTower4,},
        [Technologies.UP1_Palisade]             = {Entities.PB_WallDistorted,},
        [Technologies.UP1_PalisadeDark]         = {Entities.PB_DarkWallDistorted,},
    },

    -- Technology hack for Kerberos/Kala
    TechnologyAlternateHack = {
        [Technologies.B_Tower]                  = Technologies.B_TowerDark,
        [Technologies.B_BallistaTower]          = Technologies.B_BallistaTowerDark,
        [Technologies.B_CannonTower]            = Technologies.B_CannonTowerDark,
        [Technologies.B_Wall]                   = Technologies.B_WallDark,
        [Technologies.UP1_Palisade]             = Technologies.UP1_PalisadeDark,
        [Technologies.UP1_Tower]                = Technologies.UP1_TowerDark,
        [Technologies.UP2_Tower]                = Technologies.UP2_TowerDark,
    },

    -- Building construction restricted by rights
    RightsToCheckForConstruction = {
        [Technologies.B_Tavern]                 = PlayerRight.Tavern,
        [Technologies.B_Archery]                = PlayerRight.ShootingRange,
        [Technologies.B_Barracks]               = PlayerRight.Barracks,
        [Technologies.B_Stables]                = PlayerRight.Barn,
        [Technologies.B_Foundry]                = PlayerRight.Foundry,
        [Technologies.B_Alchemist]              = PlayerRight.Alchemist,
        [Technologies.B_Brickworks]             = PlayerRight.Brickmaker,
        [Technologies.B_Blacksmith]             = PlayerRight.Smithy,
        [Technologies.B_GunsmithWorkshop]       = PlayerRight.GunWorkshop,
        [Technologies.B_Sawmill]                = PlayerRight.Sawmill,
        [Technologies.B_StoneMason]             = PlayerRight.MasonHut,
        [Technologies.B_MasterBuilderWorkshop]  = PlayerRight.ArchitectShop,
        [Technologies.B_Bridge]                 = PlayerRight.Bridge,
        [Technologies.B_Bank]                   = PlayerRight.Bank,
        [Technologies.B_Weathermachine]         = PlayerRight.WeatherTower,
        [Technologies.B_PowerPlant]             = PlayerRight.PowerPlant,
        [Technologies.B_Tower]                  = PlayerRight.WatchTower,
        [Technologies.B_Residence]              = PlayerRight.House,
        [Technologies.B_Farm]                   = PlayerRight.Farm,
        [Technologies.B_University]             = PlayerRight.Highschool,
        [Technologies.B_Village]                = PlayerRight.VillageCenter,
        [Technologies.B_Monastery]              = PlayerRight.Chapel,
        [Technologies.B_Market]                 = PlayerRight.Store,
        [Technologies.B_Claymine]               = PlayerRight.ClayPit,
        [Technologies.B_Ironmine]               = PlayerRight.IronPit,
        [Technologies.B_Stonemine]              = PlayerRight.StonePit,
        [Technologies.B_Sulfurmine]             = PlayerRight.SulfurPit,
        [Technologies.B_Palisade]               = PlayerRight.Palisade,
        [Technologies.B_Wall]                   = PlayerRight.Wall,
        [Technologies.B_BallistaTower]          = PlayerRight.BallistaTower,
        [Technologies.B_CannonTower]            = PlayerRight.CannonTower,
        [Technologies.B_Mercenary]              = PlayerRight.MercenaryCamp,
        [Technologies.B_Headquarter]            = PlayerRight.Keep,
        [Technologies.B_Outpost]                = PlayerRight.Outpost,
        [Technologies.B_BearCage]               = PlayerRight.BearCage,
        [Technologies.B_DogCage]                = PlayerRight.DogCage,
        [Technologies.B_PitchPit]               = PlayerRight.PitchPit,
        [Technologies.B_Traphole]               = PlayerRight.Traphole,
        [Technologies.B_ExecutionerPlace]       = PlayerRight.ExecutionerPlace,
        [Technologies.B_Beautification01]       = PlayerRight.Beautification1,
        [Technologies.B_Beautification02]       = PlayerRight.Beautification2,
        [Technologies.B_Beautification03]       = PlayerRight.Beautification3,
        [Technologies.B_Beautification04]       = PlayerRight.Beautification4,
        [Technologies.B_Beautification05]       = PlayerRight.Beautification5,
        [Technologies.B_Beautification06]       = PlayerRight.Beautification6,
        [Technologies.B_Beautification07]       = PlayerRight.Beautification7,
        [Technologies.B_Beautification08]       = PlayerRight.Beautification8,
        [Technologies.B_Beautification09]       = PlayerRight.Beautification9,
        [Technologies.B_Beautification10]       = PlayerRight.Beautification10,
        [Technologies.B_Beautification11]       = PlayerRight.Beautification11,
        [Technologies.B_Beautification12]       = PlayerRight.Beautification12,
    },

    -- Building upgrade restricted by rights
    RightsToCheckForUpgrade = {
        [Technologies.UP1_Tower]            = PlayerRight.BallistaTower,
        [Technologies.UP2_Tower]            = PlayerRight.CannonTower,
        [Technologies.UP3_Tower]            = PlayerRight.FalconryTower,
        [Technologies.UP1_Market]           = PlayerRight.Market,
        [Technologies.UP1_Tavern]           = PlayerRight.Inn,
        [Technologies.UP1_University]       = PlayerRight.University,
        [Technologies.UP1_Residence]        = PlayerRight.Cottage,
        [Technologies.UP2_Residence]        = PlayerRight.Manor,
        [Technologies.UP1_Farm]             = PlayerRight.Mill,
        [Technologies.UP2_Farm]             = PlayerRight.Estate,
        [Technologies.UP1_Archery]          = PlayerRight.Archery,
        [Technologies.UP1_Barracks]         = PlayerRight.Garnison,
        [Technologies.UP1_Stables]          = PlayerRight.Stable,
        [Technologies.UP1_Foundry]          = PlayerRight.CannonFactory,
        [Technologies.UP1_Alchemist]        = PlayerRight.Laboratory,
        [Technologies.UP1_Brickworks]       = PlayerRight.Brickworks,
        [Technologies.UP1_Blacksmith]       = PlayerRight.Blacksmith,
        [Technologies.UP2_Blacksmith]       = PlayerRight.FinishingSmithy,
        [Technologies.UP1_GunsmithWorkshop] = PlayerRight.GunFactory,
        [Technologies.UP1_Sawmill]          = PlayerRight.LumberMill,
        [Technologies.UP1_StoneMason]       = PlayerRight.MasonWorkshop,
        [Technologies.UP1_Bank]             = PlayerRight.Treasury,
        [Technologies.UP1_Village]          = PlayerRight.TownCenter,
        [Technologies.UP2_Village]          = PlayerRight.CityCenter,
        [Technologies.UP1_Monastery]        = PlayerRight.Church,
        [Technologies.UP2_Monastery]        = PlayerRight.Cathedral,
        [Technologies.UP1_Headquarter]      = PlayerRight.Fortress,
        [Technologies.UP2_Headquarter]      = PlayerRight.Zitadel,
        [Technologies.UP1_Claymine]         = PlayerRight.ClayGallery,
        [Technologies.UP2_Claymine]         = PlayerRight.ClayMine,
        [Technologies.UP1_Ironmine]         = PlayerRight.IronGallery,
        [Technologies.UP2_Ironmine]         = PlayerRight.IronMine,
        [Technologies.UP1_Stonemine]        = PlayerRight.StoneGallery,
        [Technologies.UP2_Stonemine]        = PlayerRight.StoneMine,
        [Technologies.UP1_Sulfurmine]       = PlayerRight.SulfurGallery,
        [Technologies.UP2_Sulfurmine]       = PlayerRight.SulfurMine,
        [Technologies.UP1_Palisade]         = PlayerRight.Wall,
        [Technologies.UP1_Outpost]          = PlayerRight.Fort,
        [Technologies.UP2_Outpost]          = PlayerRight.Bastille,
    },

    -- Replacement types
    WallReplacerMap = {
        [Entities.XD_Palisade_Replacer]     = Entities.PB_PalisadeDistorted,
        [Entities.XD_PalisadeGate_Replacer] = Entities.PB_PalisadeStraightGate,
        [Entities.XD_DarkWall_Replacer]     = Entities.PB_DarkWallDistorted,
        [Entities.XD_DarkWallGate_Replacer] = Entities.PB_DarkWallStraightGate,
        [Entities.XD_Wall_Replacer]         = Entities.PB_WallDistorted,
        [Entities.XD_WallGate_Replacer]     = Entities.PB_WallStraightGate,
    },
}

