--- 
--- Configuration for construction limits
--- 

Stronghold.Construction.Config = {
    TowerDistance = 1500,
    LightBricksFactor = 1.2,

    -- Limit of recruiter buildings
    RecruitBuildingAmounts = {
        [Entities.PB_Headquarters1] = 6,
        [Entities.PB_Headquarters2] = 9,
        [Entities.PB_Headquarters3] = 12,
        [Entities.PB_VillageCenter1] = 2,
        [Entities.PB_VillageCenter2] = 4,
        [Entities.PB_VillageCenter3] = 6,
    },
    -- Limit of cannon factories
    SmeltingBuildingAmounts = {
        [Entities.PB_Headquarters1] = 2,
        [Entities.PB_Headquarters2] = 4,
        [Entities.PB_Headquarters3] = 6,
        [Entities.PB_VillageCenter1] = 1,
        [Entities.PB_VillageCenter2] = 2,
        [Entities.PB_VillageCenter3] = 3,
    },

    -- Check types for construction technology
    TypesToCheckForConstruction = {
        [Technologies.B_Beautification01]       = {Entities.PB_Beautification01},
        [Technologies.B_Beautification02]       = {Entities.PB_Beautification02},
        [Technologies.B_Beautification03]       = {Entities.PB_Beautification03},
        [Technologies.B_Beautification04]       = {Entities.PB_Beautification04},
        [Technologies.B_Beautification05]       = {Entities.PB_Beautification05},
        [Technologies.B_Beautification06]       = {Entities.PB_Beautification06},
        [Technologies.B_Beautification07]       = {Entities.PB_Beautification07},
        [Technologies.B_Beautification08]       = {Entities.PB_Beautification08},
        [Technologies.B_Beautification09]       = {Entities.PB_Beautification09},
        [Technologies.B_Beautification10]       = {Entities.PB_Beautification10},
        [Technologies.B_Beautification11]       = {Entities.PB_Beautification11},
        [Technologies.B_Beautification12]       = {Entities.PB_Beautification12},

        [Technologies.B_Archery]                = {Entities.PB_Archery1, Entities.PB_Archery2,},
        [Technologies.B_Barracks]               = {Entities.PB_Barracks1, Entities.PB_Barracks2,},
        [Technologies.B_Foundry]                = {Entities.PB_Foundry1, Entities.PB_Foundry2,},
        [Technologies.B_Stables]                = {Entities.PB_Stable1, Entities.PB_Stable2,},
        [Technologies.B_Tower]                  = {Entities.PB_Tower1, Entities.PB_Tower2, Entities.PB_Tower3,},

        [Technologies.B_Alchemist]              = {Entities.PB_Alchemist1, Entities.PB_Alchemist2,},
        [Technologies.B_Bank]                   = {Entities.PB_Bank1, Entities.PB_Bank2,},
        [Technologies.B_Blacksmith]             = {Entities.PB_Blacksmith1, Entities.PB_Blacksmith2, Entities.PB_Blacksmith3,},
        [Technologies.B_Brickworks]             = {Entities.PB_Brickworks1, Entities.PB_Brickworks2,},
        [Technologies.B_Farm]                   = {Entities.PB_Farm1, Entities.PB_Farm2, Entities.PB_Farm3},
        [Technologies.B_GunsmithWorkshop]       = {Entities.PB_GunsmithWorkshop1, Entities.PB_GunsmithWorkshop2,},
        [Technologies.B_Monastery]              = {Entities.PB_Monastery1, Entities.PB_Monastery2, Entities.PB_Monastery3,},
        [Technologies.B_MasterBuilderWorkshop]  = {Entities.PB_MasterBuilderWorkshop1,},
        [Technologies.B_Market]                 = {Entities.PB_Market1, Entities.PB_Market2,},
        [Technologies.B_PowerPlant]             = {Entities.PB_PowerPlant1,},
        [Technologies.B_Residence]              = {Entities.PB_Residence1, Entities.PB_Residence2, Entities.PB_Residence3,},
        [Technologies.B_Sawmill]                = {Entities.PB_Sawmill1, Entities.PB_Sawmill2,},
        [Technologies.B_StoneMason]             = {Entities.PB_StoneMason1, Entities.PB_StoneMason2,},
        [Technologies.B_Tavern]                 = {Entities.PB_Tavern1, Entities.PB_Tavern2,},
        [Technologies.B_University]             = {Entities.PB_University1, Entities.PB_University2,},
        [Technologies.B_Village]                = {Entities.PB_VillageCenter1, Entities.PB_VillageCenter2, Entities.PB_VillageCenter3,},
        [Technologies.B_Weathermachine]         = {Entities.PB_WeatherTower1,},
    },

    -- Check types for upgrade technologies
    TypesToCheckForUpgrade = {
        [Technologies.UP1_Alchemist]            = {Entities.PB_Alchemist2,},
        [Technologies.UP1_Archery]              = {Entities.PB_Archery2,},
        [Technologies.UP1_Bank]                 = {Entities.PB_Bank2},
        [Technologies.UP1_Barracks]             = {Entities.PB_Barracks2,},
        [Technologies.UP1_Blacksmith]           = {Entities.PB_Blacksmith2,Entities.PB_Blacksmith3,},
        [Technologies.UP1_Brickworks]           = {Entities.PB_Brickworks2,},
        [Technologies.UP1_Foundry]              = {Entities.PB_Foundry2,},
        [Technologies.UP1_GunsmithWorkshop]     = {Entities.PB_GunsmithWorkshop2,},
        [Technologies.UP1_Market]               = {Entities.PB_Market2,},
        [Technologies.UP1_Monastery]            = {Entities.PB_Monastery2, Entities.PB_Monastery3,},
        [Technologies.UP1_Sawmill]              = {Entities.PB_Sawmill2,},
        [Technologies.UP1_Stables]              = {Entities.PB_Stable2,},
        [Technologies.UP1_StoneMason]           = {Entities.PB_StoneMason2,},
        [Technologies.UP1_Tavern]               = {Entities.PB_Tavern2,},
        [Technologies.UP1_Tower]                = {Entities.PB_Tower2, Entities.PB_Tower3},
        [Technologies.UP1_University]           = {Entities.PB_University2,},

        [Technologies.UP2_Blacksmith]           = {Entities.PB_Blacksmith1,Entities.PB_Blacksmith3,},
        [Technologies.UP2_Monastery]            = {Entities.PB_Monastery1, Entities.PB_Monastery3,},
        [Technologies.UP2_Tower]                = {Entities.PB_Tower1, Entities.PB_Tower3,},
    },

    -- Building construction restricted by rights
    -- FIXME: Beautifications?
    RightsToCheckForConstruction = {
        [Technologies.B_Tavern]                 = PlayerRight.Tavern,
        [Technologies.B_Archery]                = PlayerRight.ShootingRange,
        [Technologies.B_Barracks]               = PlayerRight.Barracks,
        [Technologies.B_Stables]                = PlayerRight.Barn,
        [Technologies.B_Foundry]                = PlayerRight.Foundry,
        [Technologies.B_Alchemist]              = PlayerRight.Alchemist,
        [Technologies.B_Brickworks]             = PlayerRight.Brickmaker,
        [Technologies.B_Blacksmith]             = PlayerRight.Smithy,
        [Technologies.B_GunsmithWorkshop]       = PlayerRight.GunWorkshop,
        [Technologies.B_Sawmill]                = PlayerRight.Sawmill,
        [Technologies.B_StoneMason]             = PlayerRight.MasonHut,
        [Technologies.B_MasterBuilderWorkshop]  = PlayerRight.ArchitectShop,
        [Technologies.B_Bridge]                 = PlayerRight.Bridge,
        [Technologies.B_Bank]                   = PlayerRight.Bank,
        [Technologies.B_Weathermachine]         = PlayerRight.WeatherTower,
        [Technologies.B_PowerPlant]             = PlayerRight.PowerPlant,
        [Technologies.B_Tower]                  = PlayerRight.WatchTower,
        [Technologies.B_Residence]              = PlayerRight.House,
        [Technologies.B_Farm]                   = PlayerRight.Farm,
        [Technologies.B_University]             = PlayerRight.Highschool,
        [Technologies.B_Village]                = PlayerRight.VillageCenter,
        [Technologies.B_Monastery]              = PlayerRight.Chapel,
        [Technologies.B_Market]                 = PlayerRight.Store,
        [Technologies.B_Claymine]               = PlayerRight.ClayPit,
        [Technologies.B_Ironmine]               = PlayerRight.IronPit,
        [Technologies.B_Stonemine]              = PlayerRight.StonePit,
        [Technologies.B_Sulfurmine]             = PlayerRight.SulfurPit,
        [Technologies.B_Palisade]               = PlayerRight.Palisade,
        [Technologies.B_Wall]                   = PlayerRight.Wall,
        [Technologies.B_Beautification01]       = PlayerRight.Beautification1,
        [Technologies.B_Beautification02]       = PlayerRight.Beautification2,
        [Technologies.B_Beautification03]       = PlayerRight.Beautification3,
        [Technologies.B_Beautification04]       = PlayerRight.Beautification4,
        [Technologies.B_Beautification05]       = PlayerRight.Beautification5,
        [Technologies.B_Beautification06]       = PlayerRight.Beautification6,
        [Technologies.B_Beautification07]       = PlayerRight.Beautification7,
        [Technologies.B_Beautification08]       = PlayerRight.Beautification8,
        [Technologies.B_Beautification09]       = PlayerRight.Beautification9,
        [Technologies.B_Beautification10]       = PlayerRight.Beautification10,
        [Technologies.B_Beautification11]       = PlayerRight.Beautification11,
        [Technologies.B_Beautification12]       = PlayerRight.Beautification12,
    },

    -- Building upgrade restricted by rights
    RightsToCheckForUpgrade = {
        [Technologies.UP1_Tower]            = PlayerRight.BallistaTower,
        [Technologies.UP2_Tower]            = PlayerRight.CannonTower,
        [Technologies.UP1_Market]           = PlayerRight.Market,
        [Technologies.UP1_Tavern]           = PlayerRight.Inn,
        [Technologies.UP1_University]       = PlayerRight.University,
        [Technologies.UP1_Residence]        = PlayerRight.Cottage,
        [Technologies.UP2_Residence]        = PlayerRight.Manor,
        [Technologies.UP1_Farm]             = PlayerRight.Mill,
        [Technologies.UP2_Farm]             = PlayerRight.Estate,
        [Technologies.UP1_Archery]          = PlayerRight.Archery,
        [Technologies.UP1_Barracks]         = PlayerRight.Garnison,
        [Technologies.UP1_Stables]          = PlayerRight.Stable,
        [Technologies.UP1_Foundry]          = PlayerRight.CannonFactory,
        [Technologies.UP1_Alchemist]        = PlayerRight.Laboratory,
        [Technologies.UP1_Brickworks]       = PlayerRight.Brickworks,
        [Technologies.UP1_Blacksmith]       = PlayerRight.Blacksmith,
        [Technologies.UP2_Blacksmith]       = PlayerRight.FinishingSmithy,
        [Technologies.UP1_GunsmithWorkshop] = PlayerRight.GunFactory,
        [Technologies.UP1_Sawmill]          = PlayerRight.LumberMill,
        [Technologies.UP1_StoneMason]       = PlayerRight.MasonWorkshop,
        [Technologies.UP1_Bank]             = PlayerRight.Treasury,
        [Technologies.UP1_Village]          = PlayerRight.TownCenter,
        [Technologies.UP2_Village]          = PlayerRight.CityCenter,
        [Technologies.UP1_Monastery]        = PlayerRight.Church,
        [Technologies.UP2_Monastery]        = PlayerRight.Cathedral,
        [Technologies.UP1_Headquarter]      = PlayerRight.Fortress,
        [Technologies.UP2_Headquarter]      = PlayerRight.Zitadel,
        [Technologies.UP1_Claymine]         = PlayerRight.ClayGallery,
        [Technologies.UP2_Claymine]         = PlayerRight.ClayMine,
        [Technologies.UP1_Ironmine]         = PlayerRight.IronGallery,
        [Technologies.UP2_Ironmine]         = PlayerRight.IronMine,
        [Technologies.UP1_Stonemine]        = PlayerRight.StoneGallery,
        [Technologies.UP2_Stonemine]        = PlayerRight.StoneMine,
        [Technologies.UP1_Sulfurmine]       = PlayerRight.SulfurGallery,
        [Technologies.UP2_Sulfurmine]       = PlayerRight.SulfurMine,
        [Technologies.UP1_Palisade]         = PlayerRight.Wall,
    },
}

