--- 
--- Constants for Rights
--- 

-- Genders
Gender = {
    Male = 1,
    Female = 2
}

-- Ranks to achive
PlayerRank = {
    Commoner = 0,
    Noble = 1,
    Mayor = 2,
    Earl = 3,
    Baron = 4,
    Count = 5,
    Margrave = 6,
    Duke = 7
};

-- Types of conditions for promotion
PlayerDuty = {
    Headquarters = 1,
    Cathedral = 2,
    Settlers = 3,
    Soldiers = 4,
    Buildings = 5,
    Beautification = 6,
    Custom = 7,
    Technology = 8,
    Noble = 9,
}

-- Rights for the player
PlayerRight = {
    -- Measures
    MeasureLevyTax = 1,
    MeasureLawAndOrder = 2,
    FoodDistribution = 3,
    MeasureFolkloreFeast = 4,
    MeasureOrgy = 5,

    -- Units
    SwordMilitia = 6,
    SwordSquire = 7,
    SwordLong = 8,
    SwordGuardist = 9,
    SpearMilitia = 10,
    SpearLancer = 11,
    SpearLandsknecht = 12,
    SpearHalberdier = 13,
    ArcherMilitia = 14,
    ArcherLongbow = 15,
    ArcherCrossbow = 16,
    ArcherPavease = 17,
    RifleHandgunner = 18,
    RifleMusketman = 19,
    CavalryHobilar = 20,
    CavalryCrusader = 21,
    CavalryKnight = 22,
    CavalryTemplar = 23,
    BombardCannon = 24,
    BronzeCannon = 25,
    IronCannon = 26,
    SiegeCannon = 27,
    BanditSwordStrong = 28,
    BanditSwordWeak = 29,
    BanditBow = 30,
    BarbarianStrong = 31,
    BarbarianWeak = 32,
    BlackKnightStrong = 33,
    BlackKnightWeak = 34,
    BlackKnightGuard = 35,
    Bearman = 36,
    Skirmisher = 37,
    Serf = 38,
    Scout = 39,
    Thief = 40,

    -- Buildings
    BallistaTower = 41,
    CannonTower = 42,
    Inn = 43,
    University = 44,
    Market = 45,
    Cottage = 46,
    Manor = 47,
    Mill = 48,
    Estate = 49,
    Archery = 50,
    Garnison = 51,
    Stables = 52,
    CannonFactory = 53,
    Tavern = 54,
    ShootingRange = 55,
    Barracks = 56,
    Barn = 57,
    Foundry = 58,
    Brickmaker = 59,
    Brickworks = 60,
    Smithy = 61,
    Blacksmith = 62,
    FinishingSmithy = 63,
    GunWorkshop = 64,
    GunFactory = 65,
    Sawmill = 66,
    LumberMill = 67,
    MasonHut = 68,
    MasonWorkshop = 69,
    Alchemist = 70,
    Laboratory = 71,
    ArchitectShop = 72,
    Bridge = 73,
    Bank = 74,
    Treasury = 75,
    WeatherTower = 76,
    PowerPlant = 77,
    WatchTower = 78,
    House = 79,
    Farm = 80,
    Highschool = 81,
    VillageCenter = 82,
    TownCenter = 83,
    CityCenter = 84,
    Chapel = 85,
    Church = 86,
    Cathedral = 87,
    Store = 88,
    Keep = 89,
    Fortress = 90,
    Zitadel = 91,
    ClayPit = 92,
    IronPit = 93,
    StonePit = 94,
    SulfurPit = 95,
    ClayGallery = 96,
    IronGallery = 97,
    StoneGallery = 98,
    SulfurGallery = 99,
    ClayMine = 100,
    IronMine = 101,
    StoneMine = 102,
    SulfurMine = 103,

    -- Beautifications
    Beautification1 = 104,
    Beautification2 = 105,
    Beautification3 = 106,
    Beautification4 = 107,
    Beautification5 = 108,
    Beautification6 = 109,
    Beautification7 = 110,
    Beautification8 = 111,
    Beautification9 = 112,
    Beautification10 = 113,
    Beautification11 = 114,
    Beautification12 = 115,

    -- Walls
    Palisade = 116,
    Wall = 117,
}

