--- 
--- Config for AI
--- 

Stronghold.AI.Config = {
    VagabondPlayerID = 7,
    VagabondPlayerColor = 14,
    NeutralPlayerID = 8,
    NeutralPlayerColor = 14,

    Movement = {
        RegularSpeedFactor = 0.7,
        AttackSpeedFactor = 1.0,
        RunToWalk = {
            ["TL_LEADER_WALK_BATTLE"] = "TL_LEADER_WALK",
            ["TL_ASSASSIN_WALK_BATTLE"] = "TL_ASSASSIN_WALK",
            ["TL_SERF_WALK_BATTLE"] = "TL_SERF_WALK",
        },
        WalkToRun = {
            ["TL_LEADER_WALK"] = "TL_LEADER_WALK_BATTLE",
            ["TL_ASSASSIN_WALK"] = "TL_ASSASSIN_WALK_BATTLE",
            ["TL_SERF_WALK"] = "TL_SERF_WALK_BATTLE",
        },
    },

    MigratoryAnimal = {
        RegularSpeedFactor = 1.0,
        FleeingSpeedFactor = 2.0,

        [Entities.XA_Bear1] = true,
        [Entities.XA_Chicken1] = true,
        [Entities.XA_Chicken2] = true,
        [Entities.XA_Chicken3] = true,
        [Entities.XA_Cow1] = true,
        [Entities.XA_Cow2] = true,
        [Entities.XA_Cow3] = true,
        [Entities.XA_Dromedary1] = true,
        [Entities.XA_Elephant1] = true,
        [Entities.XA_Elephant2] = true,
        [Entities.XA_Frog1] = true,
        [Entities.XA_Frog2] = true,
        [Entities.XA_Frog3] = true,
        [Entities.XA_Gazelle1] = true,
        [Entities.XA_Lion1] = true,
        [Entities.XA_Lion2] = true,
        [Entities.XA_Rabbit1] = true,
        [Entities.XA_Rabbit2] = true,
        [Entities.XA_Rabbit3] = true,
        [Entities.XA_RedDeer1] = true,
        [Entities.XA_RedDeer2] = true,
        [Entities.XA_Reindeer1] = true,
        [Entities.XA_Reindeer2] = true,
        [Entities.XA_Reindeer3] = true,
        [Entities.XA_Scorpion1] = true,
        [Entities.XA_Scorpion2] = true,
        [Entities.XA_Scorpion3] = true,
        [Entities.XA_Sheep1] = true,
        [Entities.XA_Sheep2] = true,
        [Entities.XA_Sheep3] = true,
        [Entities.XA_SheepDog1] = true,
        [Entities.XA_Squirrel1] = true,
        [Entities.XA_Tiger1] = true,
        [Entities.XA_WildBoar1] = true,
        [Entities.XA_WildBoar2] = true,
        [Entities.XA_WildBoar3] = true,
        [Entities.XA_Wolf1] = true,
        [Entities.XA_Wolf2] = true,
        [Entities.XA_Wolf3] = true,
        [Entities.XA_Wolf4] = true,
        [Entities.XA_Zebra1] = true,
    },

    AttackTargetBlacklist = {
        [Entities.PB_BearCage1] = true,
        [Entities.PB_DogCage1] = true,
        [Entities.PB_PitchPit1] = true,
        [Entities.PB_Traphole1] = true,
        [Entities.PU_Bear_Deco] = true,
        [Entities.PU_Criminal_Deco] = true,
        [Entities.PU_Dog_Deco] = true,
        [Entities.PU_Hawk_Deco] = true,
        [Entities.PU_Rat_Deco] = true,
        [Entities.PU_Watchman_Deco] = true,
        [Entities.XD_TowerConstructionSite] = true,
    },
}

